# Generated by Django 4.0.3 on 2022-03-29 13:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisers',
            fields=[
                ('Organiser_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='organiserId')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('deleted', models.BooleanField(default=False)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('eventId', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='eventId')),
                ('title', models.CharField(max_length=100)),
                ('starting_date', models.DateTimeField(auto_now_add=True)),
                ('ending_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=100)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('open', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('orgnaniser_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APIs.organisers')),
            ],
        ),
    ]
